import Head from "next/head";
import React from "react";

import Header from "../../components/Header";
import DetailFeed from "../../components/detailsPage/DetailFeed";

const DetailsPage = () => {
  return (
    <div>
      <Head>
        <title>Taktok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./TaktokLogo.png" />
      </Head>
      {/*  <Header isShow={true} /> */}
      <DetailFeed />
    </div>
  );
};

export default DetailsPage;
